Add descriptions for "page::*" and "user::*"
contao/docs-archive pull request #436
Opened 2016-11-17 13:39 UTC by lionel-m

See issue #389

2016-11-17 13:48 UTC, lionel-m commented
@aschempp and @Aybee : Does it solve the ticket #389 ?

2016-11-17 13:51 UTC, lionel-m commented
I need the German translation for `{{user::*}}` please

2016-11-18 00:28 UTC, Aybee commented
Yes this will solve ticket #389 but I thnk it had to be table `tl_member`. Am I right?

**EN**
````
+  <td><code>{{user::*}}</code></td>
+  <td>This tag will be replaced with the content of a field in the table `tl_member`
+      in relation to the current member. (replace * with the name of the field).</td>
+</tr>
+<tr>
````
**DE**
````
+  <td><code>{{user::*}}</code></td>
+  <td>Dieses Tag wird mit dem Inhalt eines Feldes von `tl_member` des angemeldeten
+      Mitglieds ersetzt (ersetzen Sie * mit dem Feldnamen).</td>
+</tr>
+<tr>
``

2016-11-18 12:05 UTC, lionel-m commented
You are right and thx for the translation.

We can also change the term "User" with "Front end user" it would be more understandable...

> Front end user properties
>
> The following insert tags allow you to display any property of the currently logged in front end user.

etc.

WDYT?

2016-11-18 14:42 UTC, Aybee commented
Maybe we should use "member" instead of "front end user" as "member" is the term in back end.

I think in german translation we also should change "angemeldeten Benutzers", which means "logged in user" to "angemeldeten Mitglieds", which means "logged in member" for whole text regarding `{{user::xxx}}`.

Also the headline "Benutzereigenschaften" should be changed to "Mitgliedereingenschaften" as in Contao we have Members (Mitglieder) and Users (Benutzer) in the Accont manager (Benutzerverwaltung) in back end.

2016-11-18 15:28 UTC, lionel-m commented
@Aybee I created a new PR for that: #436.

I agree but I added the term "front end user" once in the paragraph to avoid a confusion after with the prefix `{{user::`...

2016-11-18 15:44 UTC, Aybee commented
Looks good to me. Thank you 👍

2016-11-22 21:19 UTC, aschempp requested changes

2016-11-22 21:19 UTC, aschempp commented on manual/en/04-managing-content/insert-tags.md
> +      in relation to the current user. (replace * with the name of the field).</td>
this should be *current member*, right?

2016-11-23 00:22 UTC, Aybee commented on manual/en/04-managing-content/insert-tags.md
> +      in relation to the current user. (replace * with the name of the field).</td>
Yes, as I showed here earlier https://github.com/contao/docs/pull/436#issuecomment-261413402.

2016-11-23 08:40 UTC, aschempp commented on manual/fr/04-gestion-du-contenu/balises-insertion.md
> +      par rapport à l'utilisateur courant. (remplacez * par le nom du champ).</td>
@lionel-m does `l'utilisateur` equal *member* or is this still *user*?

2016-11-23 09:07 UTC, lionel-m commented on manual/fr/04-gestion-du-contenu/balises-insertion.md
> +      par rapport à l'utilisateur courant. (remplacez * par le nom du champ).</td>
You right it is member

> par rapport au membre courant.

2016-11-23 09:12 UTC, merged

2016-11-23 09:12 UTC, aschempp commented
Thanks a lot!

2016-11-23 11:08 UTC, lionel-m commented
@aschempp #436 and #437 are not in the 4.2 branch and master.

2016-11-23 12:01 UTC, aschempp commented
Done 😊

2016-11-23 12:06 UTC, lionel-m commented
👍